### ISSUE TITLE
作者是否考虑把后端框架换为sanic？

### ISSUE THREAD

**Issue by David-Xian66** [geeeeeeeek/python_book#1]
sanic写API比Django好写

然后把前后台融为一体，就是那种只有一个前台，然后输入特定的用户名就跳进后台

sanic更加轻量，而且反应更快

我有个亲人最近想让我做个图书管理软件，我看你这个py+vue的结构整合符合我的技术栈。所以选择了这个项目，我最近抽空看看吧，给你交几个pr

**Comment by David-Xian66** [comment]
sanic反应速度我测过的，

我组织的私密项目，后端原本是ts写的，用的是js的一个移步框架（sanic也是移步框架）但是性能在我用py sanic重写后响应时间平均提升50ms以上，原本60多ms的，直接降到十几ms

sanic的具体方法可以看他社区文档，写的很清楚

**Comment by David-Xian66** [comment]
稍稍看了下，需求有点区别，我只能fork出一个单独项目了

**Comment by geeeeeeeek** [comment]
> sanic写API比Django好写
> 
> 然后把前后台融为一体，就是那种只有一个前台，然后输入特定的用户名就跳进后台
> 
> sanic更加轻量，而且反应更快
> 
> 我有个亲人最近想让我做个图书管理软件，我看你这个py+vue的结构整合符合我的技术栈。所以选择了这个项目，我最近抽空看看吧，给你交几个pr

感觉sanic不如django流行。

**Comment by David-Xian66** [comment]
> > sanic写API比Django好写
> > 然后把前后台融为一体，就是那种只有一个前台，然后输入特定的用户名就跳进后台
> > sanic更加轻量，而且反应更快
> > 我有个亲人最近想让我做个图书管理软件，我看你这个py+vue的结构整合符合我的技术栈。所以选择了这个项目，我最近抽空看看吧，给你交几个pr
> 
> 感觉sanic不如django流行。

那是，肯定的，毕竟sanic18年才建立仓库

**Comment by David-Xian66** [comment]
@geeeeeeeek 
作者 这个项目没有 api 文档吗

这种 
![image](https://github.com/geeeeeeeek/python_book/assets/70191815/211e8ca3-a44d-4b6b-9b15-6338580fd49b)
